---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_user: sudo
  vars_files:
    - secret.yml
  tasks:
  - name: login to docker registry
    docker_login:
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"
  - name: create custom docker container
    docker_container:
      name: mycustomcontainer
      image: rilindo/myapacheweb:v1
      state: started
      network_mode: bridge
      exposed_ports: "80"
      published_ports: "80:80"
