---
- hosts: all
  vars:
    docker_opts: >
      -H unix://
      -H tcp://0.0.0.0:2375
      --log-level=debug
  remote_user: ubuntu
  become: yes
  become_user: ubuntu
  roles:
    - angstwad.docker.ubuntu
